-- CreateEnum
CREATE TYPE "Instrumento" AS ENUM ('VIOLINO', 'VIOLA', 'VIOLONCELO', 'CONTRABAIXO_ACUSTICO', 'FLAUTA', 'CLARINETA', 'CLARINETA_ALTA', 'CLARINETA_BAIXA', 'SAXOFONE_SOPRANO', 'SAXOFONE_ALTO', 'SAXOFONE_TENOR', 'SAXOFONE_BARITONO', 'TROMPETE', 'TROMBONE', 'TROMBONITO', 'BOMBARDAO', 'TUBA', 'ORGAO');

-- CreateEnum
CREATE TYPE "Tonalidade" AS ENUM ('DO_MAIOR', 'SI_BEMOL', 'MI_BEMOL');

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'USER', 'VISITANTE');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'USER';
