// src/constants/enums.ts
export enum Status {
  CULTOS_OFICIAIS = "CULTOS OFICIAIS",
  REUNIOES_JOVENS = "REUNIOES DE JOVENS",
  OFICIALIZADO = "OFICIALIZADO",
  ENSAIOS = "ENSAIOS",
  ALUNO = "ALUNO",
  ALUNAS = "ALUNAS",
  // adicione os demais...
}

export enum Funcao {
  MUSICO = "MUSICO",
  INSTRUTOR = "INSTRUTOR",
  INSTRUTORA = "INSTRUTORA",
  ENCARREGADO_REGIONAL = "ENCARREGADO REGIONAL",
  ENCARREGADO_LOCAL = "ENCARREGADO LOCAL",
  EXAMINADORA = "EXAMINADORA",

  // adicione os demais...
}

export enum EstadoCivil {
  SOLTEIRO = "SOLTEIRO",
  CASADO = "CASADO",
  DIVORCIADO = "DIVORCIADO",
  VIUVO = "VIÚVO",
  SEPARADO = "SEPARADO",
  UNIAO_ESTAVEL = "UNIÃO ESTÁVEL",
  // adicione os demais...
}
export enum Tonalidade {
  DO = "DO_MAIOR",
  SI = "SI_BEMOL",
  MI = "MI_BEMOL",
  FA = "FA_MAIO"
}

export enum Instrumento {
  VIOLINO = "VIOLINO",
  VIOLA = "VIOLA",
  VIOLONCELO = "CIOLONCELO",
  CONTRABAIXO_ACUSTICO = "CONTRABAIXO_ACUSTICO",
  FLAUTA = "FLAUTA",
  CLARINETA = "CLARINETA",
  CLARINETA_ALTA = "CLARINETA_ALTA",
  CLARINETA_BAIXA = "CLARINETA_BAIXA",
  SAXOFONE_SOPRANO = "SAXOFONE_SOPRANO",
  SAXOFONE_ALTO = "SAXOFONE_ALTO",
  SAXOFONE_TENOR = "SAXOFONE_TENOR",
  SAXOFONE_BARITONO = "SAXOFONE_BARITONO",
  TROMPETE = "TROMPETE",
  TROMBONE = "TROMBONE",
  TROMBONITO = "TROMBONITO",
  BOMBARDAO = "BOMBARDAO",
  TUBA = "TUBA",
  ORGAO = "ORGAO",
}
